# Generated by Django 6.0.5 on 2026-05-19 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_is_subscribed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subscription_expires_at',
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway_customer_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID клиента в шлюзе')),
                ('gateway_subscription_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID подписки в шлюзе')),
                ('current_period_end', models.DateTimeField(blank=True, null=True, verbose_name='Конец оплаченного периода')),
                ('renewal_count', models.PositiveIntegerField(default=0, verbose_name='Количество продлений')),
                ('status', models.CharField(choices=[('inactive', 'Неактивна'), ('active', 'Активна')], default='active', max_length=8, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'подписка',
                'verbose_name_plural': 'Подписка',
            },
        ),
    ]
