# Generated by Django 6.0.5 on 2026-05-21 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_user_subscription_expires_at_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vpnconfig',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('inactive', 'Неактивна'), ('active', 'Активна'), ('in progress', 'Оформляется')], default='in progress', max_length=12, verbose_name='Статус'),
        ),
    ]
