# Generated by Django 6.0.5 on 2026-05-22 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_vpnconfig_is_active_alter_subscription_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_subscribed',
        ),
    ]
