# Generated by Django 6.0.5 on 2026-05-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_user_is_subscribed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('inactive', 'Неактивна'), ('active', 'Активна')], default='inactive', max_length=10, verbose_name='Статус'),
        ),
    ]
